[window]
opacity = 0.85
decorations = "Full"

[window.padding]
x = 3
y = 3

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.cursor]
cursor = "#c0caf5"
text = "#15161e"

[colors.selection]
text = "#33467c"
background = "#c0caf5"

[colors.normal]
black   = "#15161e"
blue    = "#7aa2f7"
cyan    = "#7dcfff"
green   = "#9ece6a"
magenta = "#bb9af7"
red     = "#f7768e"
white   = "#a9b1d6"
yellow  = "#e0af68"

[colors.bright] 
black   = "#414868"
blue    = "#7aa2f7"
cyan    = "#7dcfff"
green   = "#9ece6a"
magenta = "#bb9af7"
red     = "#f7768e"
white   = "#c0caf5"
yellow  = "#e0af68"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]

[env]
TERM = "xterm-256color"

